# SPDX-License-Identifier: AGPL-3.0-or-later
# SPDX-FileCopyrightText: 2026 swiss-ehealth contributors
"""Importing this package registers every table on the metadata."""

from ehealth.models.audit import (
    AuditAction,
    AuditEvent,
    AuditOutcome,
    ChangeOperation,
    LedgerAnchor,
    RecordRevision,
)
from ehealth.models.auth import (
    AccountStatus,
    AssuranceLevel,
    AuthSession,
    IdentityAccount,
    OidcFlow,
    OtpChallenge,
    SessionState,
)
from ehealth.models.base import Confidentiality, Purpose
from ehealth.models.clinical import (
    AuthorisationStatus,
    DispensingCategory,
    DocumentStatus,
    Dossier,
    DossierDocument,
    DossierStatus,
    MedicationEventKind,
    MedicationStatement,
    MedicationStatus,
    MedicinalProduct,
    NarcoticSchedule,
)
from ehealth.models.core import (
    CANTONS,
    PRESCRIBING_PROFESSIONS,
    IdentificationMethod,
    MedicalProfession,
    Organization,
    Person,
    PersonRole,
    PersonRoleKind,
    PersonStatus,
    ProfessionalCredential,
    ProfessionalRegister,
    RoleStatus,
)
from ehealth.models.governance import (
    AccessGrant,
    Consent,
    ConsentRule,
    GrantStatus,
    IssuedToken,
    ParticipationStatus,
    RuleEffect,
    TokenKind,
)

__all__ = [
    "CANTONS",
    "PRESCRIBING_PROFESSIONS",
    "AccessGrant",
    "AccountStatus",
    "AssuranceLevel",
    "AuditAction",
    "AuditEvent",
    "AuditOutcome",
    "AuthorisationStatus",
    "AuthSession",
    "ChangeOperation",
    "Confidentiality",
    "Consent",
    "ConsentRule",
    "DispensingCategory",
    "DocumentStatus",
    "Dossier",
    "DossierDocument",
    "DossierStatus",
    "GrantStatus",
    "IdentificationMethod",
    "IdentityAccount",
    "IssuedToken",
    "LedgerAnchor",
    "MedicationEventKind",
    "MedicationStatement",
    "MedicationStatus",
    "MedicalProfession",
    "MedicinalProduct",
    "NarcoticSchedule",
    "OidcFlow",
    "Organization",
    "OtpChallenge",
    "Person",
    "PersonRole",
    "PersonRoleKind",
    "PersonStatus",
    "ProfessionalCredential",
    "ProfessionalRegister",
    "RoleStatus",
    "ParticipationStatus",
    "Purpose",
    "RecordRevision",
    "RuleEffect",
    "SessionState",
    "TokenKind",
]
