# SPDX-License-Identifier: AGPL-3.0-or-later
"""initial schema

Revision ID: dbc126357ff5
Revises: 
Created: 2026-08-09 10:14:50.438786

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
import ehealth.models.base

#: The application-facing schema version this migration brings the database
#: to. Kept next to the revision hash because the hash means nothing to a
#: human, and this number is what the changelog and /v1/version talk about.
SCHEMA_VERSION = 4

revision: str = 'dbc126357ff5'
down_revision: str | None = None
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    _create_tables()
    # Stamp the schema version inside the same transaction as the DDL, so the
    # database can never claim a version it does not actually have.
    from ehealth.schema import stamp_schema_version
    from ehealth.version import version_label

    stamp_schema_version(op.get_bind(), SCHEMA_VERSION, applied_by=version_label())


def _create_tables() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_event',
    sa.Column('chain_id', sa.String(length=32), nullable=False),
    sa.Column('seq', sa.BigInteger(), nullable=False),
    sa.Column('occurred_at', ehealth.models.base.UtcDateTime(), nullable=False),
    sa.Column('actor_uid', sa.String(length=32), nullable=True),
    sa.Column('actor_kind', sa.String(length=32), nullable=False),
    sa.Column('on_behalf_of_uid', sa.String(length=32), nullable=True),
    sa.Column('actor_organization_uid', sa.String(length=32), nullable=True),
    sa.Column('action', sa.String(length=48), nullable=False),
    sa.Column('outcome', sa.String(length=16), nullable=False),
    sa.Column('purpose', sa.String(length=32), nullable=True),
    sa.Column('resource_type', sa.String(length=40), nullable=False),
    sa.Column('resource_uid', sa.String(length=64), nullable=True),
    sa.Column('dossier_uid', sa.String(length=32), nullable=True),
    sa.Column('token_jti', sa.String(length=48), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('client_ip_hash', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=200), nullable=True),
    sa.Column('detail', ehealth.models.base.JsonType, nullable=False),
    sa.Column('payload_version', sa.Integer(), nullable=False),
    sa.Column('software_version', sa.String(length=40), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('prev_hash', sa.String(length=64), nullable=False),
    sa.Column('entry_hash', sa.String(length=64), nullable=False),
    sa.Column('signature', sa.String(length=128), nullable=False),
    sa.Column('key_id', sa.String(length=48), nullable=False),
    sa.Column('algorithm', sa.String(length=24), nullable=False),
    sa.Column('uid', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('uid', name=op.f('pk_audit_event')),
    sa.UniqueConstraint('chain_id', 'seq', name='uq_audit_event_chain_seq')
    )
    with op.batch_alter_table('audit_event', schema=None) as batch_op:
        batch_op.create_index('ix_audit_action_ts', ['action', 'occurred_at'], unique=False)
        batch_op.create_index('ix_audit_actor_ts', ['actor_uid', 'occurred_at'], unique=False)
        batch_op.create_index('ix_audit_chain_seq', ['chain_id', 'seq'], unique=False)
        batch_op.create_index('ix_audit_dossier_ts', ['dossier_uid', 'occurred_at'], unique=False)
        batch_op.create_index('ix_audit_resource', ['resource_type', 'resource_uid'], unique=False)

    op.create_table('issued_token',
    sa.Column('jti', sa.String(length=48), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('subject_uid', sa.String(length=32), nullable=False),
    sa.Column('dossier_uid', sa.String(length=32), nullable=True),
    sa.Column('grant_uid', sa.String(length=32), nullable=True),
    sa.Column('session_uid', sa.String(length=32), nullable=True),
    sa.Column('issued_at', ehealth.models.base.UtcDateTime(), nullable=False),
    sa.Column('expires_at', ehealth.models.base.UtcDateTime(), nullable=False),
    sa.Column('revoked_at', ehealth.models.base.UtcDateTime(), nullable=True),
    sa.Column('revocation_reason', sa.String(length=120), nullable=True),
    sa.Column('cnf_jkt', sa.String(length=64), nullable=True),
    sa.Column('max_uses', sa.Integer(), nullable=False),
    sa.Column('use_count', sa.Integer(), nullable=False),
    sa.Column('last_used_at', ehealth.models.base.UtcDateTime(), nullable=True),
    sa.Column('parent_jti', sa.String(length=48), nullable=True),
    sa.Column('key_id', sa.String(length=48), nullable=False),
    sa.Column('algorithm', sa.String(length=24), nullable=False),
    sa.Column('created_at', ehealth.models.base.UtcDateTime(), nullable=False),
    sa.Column('updated_at', ehealth.models.base.UtcDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('jti', name=op.f('pk_issued_token'))
    )
    with op.batch_alter_table('issued_token', schema=None) as batch_op:
        batch_op.create_index('ix_issued_token_expires', ['expires_at'], unique=False)
        batch_op.create_index('ix_issued_token_subject', ['subject_uid', 'kind'], unique=False)

    op.create_table('ledger_anchor',
    sa.Column('period', sa.String(length=24), nullable=False),
    sa.Column('previous_anchor_hash', sa.String(length=64), nullable=False),
    sa.Column('merkle_root', sa.String(length=64), nullable=False),
    sa.Column('anchor_hash', sa.String(length=64), nullable=False),
    sa.Column('chain_count', sa.Integer(), nullable=False),
    sa.Column('event_count', sa.Integer(), nullable=False),
    sa.Column('signature', sa.String(length=128), nullable=False),
    sa.Column('key_id', sa.String(length=48), nullable=False),
    sa.Column('algorithm', sa.String(length=24), nullable=False),
    sa.Column('software_version', sa.String(length=40), nullable=False),
    sa.Column('created_at', ehealth.models.base.UtcDateTime(), nullable=False),
    sa.Column('external_reference', sa.String(length=300), nullable=True),
    sa.Column('uid', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('uid', name=op.f('pk_ledger_anchor')),
    sa.UniqueConstraint('period', name='uq_ledger_anchor_period')
    )
    with op.batch_alter_table('ledger_anchor', schema=None) as batch_op:
        batch_op.create_index('ix_ledger_anchor_created', ['created_at'], unique=False)

    op.create_table('medicinal_product',
    sa.Column('gtin', sa.String(length=14), nullable=False),
    sa.Column('swissmedic_authorisation', sa.String(length=12), nullable=True),
    sa.Column('authorisation_status', sa.String(length=16), nullable=False),
    sa.Column('authorisation_valid_until', sa.Date(), nullable=True),
    sa.Column('pharmacode', sa.String(length=7), nullable=True),
    sa.Column('name', sa.String(length=240), nullable=False),
    sa.Column('active_ingredient', sa.String(length=240), nullable=True),
    sa.Column('atc_code', sa.String(length=12), nullable=True),
    sa.Column('dose_form', sa.String(length=80), nullable=True),
    sa.Column('strength', sa.String(length=80), nullable=True),
    sa.Column('package_size', sa.String(length=60), nullable=True),
    sa.Column('marketing_authorisation_holder', sa.String(length=200), nullable=True),
    sa.Column('marketing_authorisation_holder_gln', sa.String(length=13), nullable=True),
    sa.Column('dispensing_category', sa.String(length=2), nullable=False),
    sa.Column('narcotic_schedule', sa.String(length=8), nullable=False),
    sa.Column('sl_listed', sa.Boolean(), nullable=False),
    sa.Column('sl_number', sa.String(length=20), nullable=True),
    sa.Column('withdrawn_at', sa.Date(), nullable=True),
    sa.Column('created_at', ehealth.models.base.UtcDateTime(), nullable=False),
    sa.Column('updated_at', ehealth.models.base.UtcDateTime(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('uid', name=op.f('pk_medicinal_product')),
    sa.UniqueConstraint('gtin', name='uq_medicinal_product_gtin'),
    sa.UniqueConstraint('pharmacode', name='uq_medicinal_product_pharmacode')
    )
    with op.batch_alter_table('medicinal_product', schema=None) as batch_op:
        batch_op.create_index('ix_medicinal_product_atc', ['atc_code'], unique=False)
        batch_op.create_index('ix_medicinal_product_authorisation', ['swissmedic_authorisation'], unique=False)
        batch_op.create_index('ix_medicinal_product_name', ['name'], unique=False)

    op.create_table('oidc_flow',
    sa.Column('state', sa.String(length=64), nullable=False),
    sa.Column('nonce', sa.String(length=64), nullable=False),
    sa.Column('code_verifier', sa.String(length=256), nullable=False),
    sa.Column('redirect_uri', sa.String(length=300), nullable=False),
    sa.Column('created_at', ehealth.models.base.UtcDateTime(), nullable=False),
    sa.Column('expires_at', ehealth.models.base.UtcDateTime(), nullable=False),
    sa.Column('consumed_at', ehealth.models.base.UtcDateTime(), nullable=True),
    sa.Column('client_ip_hash', sa.String(length=64), nullable=True),
    sa.Column('uid', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('uid', name=op.f('pk_oidc_flow')),
    sa.UniqueConstraint('state', name='uq_oidc_flow_state')
    )
    with op.batch_alter_table('oidc_flow', schema=None) as batch_op:
        batch_op.create_index('ix_oidc_flow_expires', ['expires_at'], unique=False)

    op.create_table('organization',
    sa.Column('che_uid', sa.String(length=9), nullable=True),
    sa.Column('gln', sa.String(length=13), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('community', sa.String(length=120), nullable=True),
    sa.Column('zsr_number', sa.String(length=7), nullable=True),
    sa.Column('canton', sa.String(length=2), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', ehealth.models.base.UtcDateTime(), nullable=False),
    sa.Column('updated_at', ehealth.models.base.UtcDateTime(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('uid', name=op.f('pk_organization')),
    sa.UniqueConstraint('che_uid', name=op.f('uq_organization_che_uid')),
    sa.UniqueConstraint('gln', name=op.f('uq_organization_gln'))
    )
    op.create_table('person',
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('identification_method', sa.String(length=24), nullable=False),
    sa.Column('ppid', sa.String(length=64), nullable=True),
    sa.Column('spid', sa.String(length=18), nullable=True),
    sa.Column('lookup_index', sa.String(length=80), nullable=True),
    sa.Column('sealed_ahvn', sa.String(length=256), nullable=True),
    sa.Column('given_name_enc', sa.String(length=512), nullable=True),
    sa.Column('family_name_enc', sa.String(length=512), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('administrative_sex', sa.String(length=16), nullable=True),
    sa.Column('contact_email_enc', sa.String(length=512), nullable=True),
    sa.Column('contact_phone_enc', sa.String(length=512), nullable=True),
    sa.Column('id_document_enc', sa.String(length=512), nullable=True),
    sa.Column('veka_number_enc', sa.String(length=512), nullable=True),
    sa.Column('created_at', ehealth.models.base.UtcDateTime(), nullable=False),
    sa.Column('updated_at', ehealth.models.base.UtcDateTime(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('uid', name=op.f('pk_person')),
    sa.UniqueConstraint('ppid', name='uq_person_ppid'),
    sa.UniqueConstraint('spid', name='uq_person_spid')
    )
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.create_index('ix_person_lookup_index', ['lookup_index'], unique=False)
        batch_op.create_index('ix_person_status', ['status'], unique=False)

    op.create_table('record_revision',
    sa.Column('entity_type', sa.String(length=40), nullable=False),
    sa.Column('entity_uid', sa.String(length=32), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('operation', sa.String(length=16), nullable=False),
    sa.Column('changed_by_uid', sa.String(length=32), nullable=True),
    sa.Column('changed_at', ehealth.models.base.UtcDateTime(), nullable=False),
    sa.Column('valid_from', ehealth.models.base.UtcDateTime(), nullable=False),
    sa.Column('valid_until', ehealth.models.base.UtcDateTime(), nullable=True),
    sa.Column('diff', ehealth.models.base.JsonType, nullable=False),
    sa.Column('state_hash', sa.String(length=64), nullable=False),
    sa.Column('audit_seq', sa.BigInteger(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('uid', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('uid', name=op.f('pk_record_revision')),
    sa.UniqueConstraint('entity_type', 'entity_uid', 'version', name='uq_revision_entity_version')
    )
    with op.batch_alter_table('record_revision', schema=None) as batch_op:
        batch_op.create_index('ix_revision_audit_seq', ['audit_seq'], unique=False)
        batch_op.create_index('ix_revision_changed_at', ['changed_at'], unique=False)
        batch_op.create_index('ix_revision_entity', ['entity_type', 'entity_uid', 'version'], unique=False)

    op.create_table('schema_metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('applied_by', sa.String(length=40), nullable=False),
    sa.Column('applied_at', ehealth.models.base.UtcDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_schema_metadata'))
    )
    op.create_table('consent',
    sa.Column('patient_uid', sa.String(length=32), nullable=False),
    sa.Column('participation', sa.String(length=16), nullable=False),
    sa.Column('default_access_level', sa.String(length=16), nullable=False),
    sa.Column('emergency_access_allowed', sa.Boolean(), nullable=False),
    sa.Column('notify_on_access', sa.Boolean(), nullable=False),
    sa.Column('withdrawn_at', ehealth.models.base.UtcDateTime(), nullable=True),
    sa.Column('evidence', ehealth.models.base.JsonType, nullable=False),
    sa.Column('created_at', ehealth.models.base.UtcDateTime(), nullable=False),
    sa.Column('updated_at', ehealth.models.base.UtcDateTime(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['patient_uid'], ['person.uid'], name=op.f('fk_consent_patient_uid'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('uid', name=op.f('pk_consent')),
    sa.UniqueConstraint('patient_uid', name='uq_consent_patient_uid')
    )
    op.create_table('dossier',
    sa.Column('patient_uid', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('opened_at', ehealth.models.base.UtcDateTime(), nullable=False),
    sa.Column('closed_at', ehealth.models.base.UtcDateTime(), nullable=True),
    sa.Column('retention_until', ehealth.models.base.UtcDateTime(), nullable=True),
    sa.Column('default_confidentiality', sa.String(length=16), nullable=False),
    sa.Column('home_community', sa.String(length=120), nullable=True),
    sa.Column('created_at', ehealth.models.base.UtcDateTime(), nullable=False),
    sa.Column('updated_at', ehealth.models.base.UtcDateTime(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['patient_uid'], ['person.uid'], name=op.f('fk_dossier_patient_uid'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('uid', name=op.f('pk_dossier')),
    sa.UniqueConstraint('patient_uid', name='uq_dossier_patient_uid')
    )
    op.create_table('identity_account',
    sa.Column('person_uid', sa.String(length=32), nullable=False),
    sa.Column('issuer', sa.String(length=200), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('email_enc', sa.String(length=512), nullable=False),
    sa.Column('email_index', sa.String(length=80), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('idp_assurance', sa.String(length=16), nullable=False),
    sa.Column('mfa_required', sa.Boolean(), nullable=False),
    sa.Column('failed_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', ehealth.models.base.UtcDateTime(), nullable=True),
    sa.Column('last_login_at', ehealth.models.base.UtcDateTime(), nullable=True),
    sa.Column('created_at', ehealth.models.base.UtcDateTime(), nullable=False),
    sa.Column('updated_at', ehealth.models.base.UtcDateTime(), nullable=False),
    sa.Column('uid', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['person_uid'], ['person.uid'], name=op.f('fk_identity_account_person_uid'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('uid', name=op.f('pk_identity_account')),
    sa.UniqueConstraint('issuer', 'subject', name='uq_account_issuer_subject'),
    sa.UniqueConstraint('person_uid', name='uq_account_person_uid')
    )
    with op.batch_alter_table('identity_account', schema=None) as batch_op:
        batch_op.create_index('ix_account_email_index', ['email_index'], unique=False)

    op.create_table('ledger_anchor_chain',
    sa.Column('anchor_uid', sa.String(length=32), nullable=False),
    sa.Column('chain_id', sa.String(length=32), nullable=False),
    sa.Column('last_seq', sa.BigInteger(), nullable=False),
    sa.Column('head_hash', sa.String(length=64), nullable=False),
    sa.Column('event_count', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['anchor_uid'], ['ledger_anchor.uid'], name=op.f('fk_ledger_anchor_chain_anchor_uid'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('uid', name=op.f('pk_ledger_anchor_chain')),
    sa.UniqueConstraint('anchor_uid', 'chain_id', name='uq_anchor_chain')
    )
    with op.batch_alter_table('ledger_anchor_chain', schema=None) as batch_op:
        batch_op.create_index('ix_anchor_chain_chain', ['chain_id', 'last_seq'], unique=False)

    op.create_table('person_role',
    sa.Column('person_uid', sa.String(length=32), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('valid_from', ehealth.models.base.UtcDateTime(), nullable=False),
    sa.Column('valid_until', ehealth.models.base.UtcDateTime(), nullable=True),
    sa.Column('granted_by_uid', sa.String(length=32), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', ehealth.models.base.UtcDateTime(), nullable=False),
    sa.Column('updated_at', ehealth.models.base.UtcDateTime(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['person_uid'], ['person.uid'], name=op.f('fk_person_role_person_uid'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('uid', name=op.f('pk_person_role')),
    sa.UniqueConstraint('person_uid', 'role', name='uq_person_role')
    )
    with op.batch_alter_table('person_role', schema=None) as batch_op:
        batch_op.create_index('ix_person_role_lookup', ['person_uid', 'role', 'status'], unique=False)

    op.create_table('professional_credential',
    sa.Column('person_uid', sa.String(length=32), nullable=False),
    sa.Column('gln', sa.String(length=13), nullable=False),
    sa.Column('register', sa.String(length=24), nullable=False),
    sa.Column('profession', sa.String(length=32), nullable=False),
    sa.Column('specialisation', sa.String(length=160), nullable=True),
    sa.Column('licence_canton', sa.String(length=2), nullable=True),
    sa.Column('licence_number', sa.String(length=64), nullable=True),
    sa.Column('licence_valid_from', sa.Date(), nullable=True),
    sa.Column('licence_valid_until', sa.Date(), nullable=True),
    sa.Column('licence_suspended', sa.Boolean(), nullable=False),
    sa.Column('zsr_number', sa.String(length=7), nullable=True),
    sa.Column('organization_uid', sa.String(length=32), nullable=True),
    sa.Column('verified_at', ehealth.models.base.UtcDateTime(), nullable=True),
    sa.Column('verification_source', sa.String(length=80), nullable=True),
    sa.Column('verification_evidence', ehealth.models.base.JsonType, nullable=False),
    sa.Column('created_at', ehealth.models.base.UtcDateTime(), nullable=False),
    sa.Column('updated_at', ehealth.models.base.UtcDateTime(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['organization_uid'], ['organization.uid'], name=op.f('fk_professional_credential_organization_uid'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['person_uid'], ['person.uid'], name=op.f('fk_professional_credential_person_uid'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('uid', name=op.f('pk_professional_credential')),
    sa.UniqueConstraint('gln', name='uq_credential_gln')
    )
    with op.batch_alter_table('professional_credential', schema=None) as batch_op:
        batch_op.create_index('ix_credential_person', ['person_uid'], unique=False)
        batch_op.create_index('ix_credential_register', ['register', 'profession'], unique=False)

    op.create_table('access_grant',
    sa.Column('dossier_uid', sa.String(length=32), nullable=False),
    sa.Column('grantee_uid', sa.String(length=32), nullable=False),
    sa.Column('grantee_kind', sa.String(length=32), nullable=False),
    sa.Column('granted_by_uid', sa.String(length=32), nullable=False),
    sa.Column('purpose', sa.String(length=32), nullable=False),
    sa.Column('access_level', sa.String(length=16), nullable=False),
    sa.Column('scopes', ehealth.models.base.JsonType, nullable=False),
    sa.Column('valid_from', ehealth.models.base.UtcDateTime(), nullable=False),
    sa.Column('valid_until', ehealth.models.base.UtcDateTime(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('revoked_at', ehealth.models.base.UtcDateTime(), nullable=True),
    sa.Column('revoked_by_uid', sa.String(length=32), nullable=True),
    sa.Column('max_uses', sa.Integer(), nullable=False),
    sa.Column('use_count', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', ehealth.models.base.UtcDateTime(), nullable=False),
    sa.Column('updated_at', ehealth.models.base.UtcDateTime(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['dossier_uid'], ['dossier.uid'], name=op.f('fk_access_grant_dossier_uid'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['granted_by_uid'], ['person.uid'], name=op.f('fk_access_grant_granted_by_uid'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['grantee_uid'], ['person.uid'], name=op.f('fk_access_grant_grantee_uid'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('uid', name=op.f('pk_access_grant'))
    )
    with op.batch_alter_table('access_grant', schema=None) as batch_op:
        batch_op.create_index('ix_grant_dossier_status', ['dossier_uid', 'status'], unique=False)
        batch_op.create_index('ix_grant_grantee_status', ['grantee_uid', 'status'], unique=False)

    op.create_table('auth_session',
    sa.Column('account_uid', sa.String(length=32), nullable=False),
    sa.Column('person_uid', sa.String(length=32), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('assurance_level', sa.String(length=16), nullable=False),
    sa.Column('auth_methods', ehealth.models.base.JsonType, nullable=False),
    sa.Column('expires_at', ehealth.models.base.UtcDateTime(), nullable=False),
    sa.Column('activated_at', ehealth.models.base.UtcDateTime(), nullable=True),
    sa.Column('revoked_at', ehealth.models.base.UtcDateTime(), nullable=True),
    sa.Column('client_ip_hash', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=200), nullable=True),
    sa.Column('created_at', ehealth.models.base.UtcDateTime(), nullable=False),
    sa.Column('updated_at', ehealth.models.base.UtcDateTime(), nullable=False),
    sa.Column('uid', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['account_uid'], ['identity_account.uid'], name=op.f('fk_auth_session_account_uid'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid', name=op.f('pk_auth_session'))
    )
    with op.batch_alter_table('auth_session', schema=None) as batch_op:
        batch_op.create_index('ix_session_account_state', ['account_uid', 'state'], unique=False)
        batch_op.create_index('ix_session_expires', ['expires_at'], unique=False)

    op.create_table('consent_rule',
    sa.Column('consent_uid', sa.String(length=32), nullable=False),
    sa.Column('subject_type', sa.String(length=24), nullable=False),
    sa.Column('subject_uid', sa.String(length=64), nullable=False),
    sa.Column('effect', sa.String(length=8), nullable=False),
    sa.Column('access_level', sa.String(length=16), nullable=False),
    sa.Column('valid_from', ehealth.models.base.UtcDateTime(), nullable=True),
    sa.Column('valid_until', ehealth.models.base.UtcDateTime(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', ehealth.models.base.UtcDateTime(), nullable=False),
    sa.Column('updated_at', ehealth.models.base.UtcDateTime(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['consent_uid'], ['consent.uid'], name=op.f('fk_consent_rule_consent_uid'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid', name=op.f('pk_consent_rule'))
    )
    with op.batch_alter_table('consent_rule', schema=None) as batch_op:
        batch_op.create_index('ix_consent_rule_consent', ['consent_uid', 'effect'], unique=False)

    op.create_table('dossier_document',
    sa.Column('dossier_uid', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('document_class', sa.String(length=80), nullable=False),
    sa.Column('mime_type', sa.String(length=120), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('confidentiality', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('author_uid', sa.String(length=32), nullable=False),
    sa.Column('author_organization_uid', sa.String(length=32), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('content_size', sa.Integer(), nullable=False),
    sa.Column('storage_ref', sa.String(length=300), nullable=True),
    sa.Column('supersedes_uid', sa.String(length=32), nullable=True),
    sa.Column('service_start', ehealth.models.base.UtcDateTime(), nullable=True),
    sa.Column('service_end', ehealth.models.base.UtcDateTime(), nullable=True),
    sa.Column('created_at', ehealth.models.base.UtcDateTime(), nullable=False),
    sa.Column('updated_at', ehealth.models.base.UtcDateTime(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['author_organization_uid'], ['organization.uid'], name=op.f('fk_dossier_document_author_organization_uid'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['author_uid'], ['person.uid'], name=op.f('fk_dossier_document_author_uid'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['dossier_uid'], ['dossier.uid'], name=op.f('fk_dossier_document_dossier_uid'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('uid', name=op.f('pk_dossier_document'))
    )
    with op.batch_alter_table('dossier_document', schema=None) as batch_op:
        batch_op.create_index('ix_document_dossier_conf', ['dossier_uid', 'confidentiality'], unique=False)
        batch_op.create_index('ix_document_dossier_created', ['dossier_uid', 'created_at'], unique=False)

    op.create_table('medication_statement',
    sa.Column('dossier_uid', sa.String(length=32), nullable=False),
    sa.Column('product_uid', sa.String(length=32), nullable=True),
    sa.Column('product_text', sa.String(length=240), nullable=True),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('confidentiality', sa.String(length=16), nullable=False),
    sa.Column('dosage', ehealth.models.base.JsonType, nullable=False),
    sa.Column('quantity', sa.String(length=60), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('effective_start', ehealth.models.base.UtcDateTime(), nullable=True),
    sa.Column('effective_end', ehealth.models.base.UtcDateTime(), nullable=True),
    sa.Column('recorded_by_uid', sa.String(length=32), nullable=False),
    sa.Column('recorded_under_credential_uid', sa.String(length=32), nullable=True),
    sa.Column('recorded_by_gln', sa.String(length=13), nullable=True),
    sa.Column('organization_uid', sa.String(length=32), nullable=True),
    sa.Column('based_on_uid', sa.String(length=32), nullable=True),
    sa.Column('offline_client_uid', sa.String(length=64), nullable=True),
    sa.Column('captured_offline_at', ehealth.models.base.UtcDateTime(), nullable=True),
    sa.Column('created_at', ehealth.models.base.UtcDateTime(), nullable=False),
    sa.Column('updated_at', ehealth.models.base.UtcDateTime(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['dossier_uid'], ['dossier.uid'], name=op.f('fk_medication_statement_dossier_uid'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_uid'], ['organization.uid'], name=op.f('fk_medication_statement_organization_uid'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_uid'], ['medicinal_product.uid'], name=op.f('fk_medication_statement_product_uid'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['recorded_by_uid'], ['person.uid'], name=op.f('fk_medication_statement_recorded_by_uid'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('uid', name=op.f('pk_medication_statement')),
    sa.UniqueConstraint('dossier_uid', 'offline_client_uid', name='uq_medstatement_offline_uid')
    )
    with op.batch_alter_table('medication_statement', schema=None) as batch_op:
        batch_op.create_index('ix_medstatement_dossier_effective', ['dossier_uid', 'effective_start'], unique=False)
        batch_op.create_index('ix_medstatement_dossier_kind', ['dossier_uid', 'kind'], unique=False)

    op.create_table('otp_challenge',
    sa.Column('session_uid', sa.String(length=32), nullable=False),
    sa.Column('account_uid', sa.String(length=32), nullable=False),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('code_hash', sa.String(length=128), nullable=False),
    sa.Column('created_at', ehealth.models.base.UtcDateTime(), nullable=False),
    sa.Column('expires_at', ehealth.models.base.UtcDateTime(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('consumed_at', ehealth.models.base.UtcDateTime(), nullable=True),
    sa.Column('delivered', sa.Boolean(), nullable=False),
    sa.Column('uid', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['session_uid'], ['auth_session.uid'], name=op.f('fk_otp_challenge_session_uid'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid', name=op.f('pk_otp_challenge'))
    )
    with op.batch_alter_table('otp_challenge', schema=None) as batch_op:
        batch_op.create_index('ix_otp_session_created', ['session_uid', 'created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """There is no going back from the initial migration.

    Dropping every table is not a rollback, it is data loss with extra steps.
    A deployment that needs to go back restores a backup.
    """
    raise NotImplementedError(
        "the initial migration is not reversible; restore from backup instead"
    )


def _unused_downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('otp_challenge', schema=None) as batch_op:
        batch_op.drop_index('ix_otp_session_created')

    op.drop_table('otp_challenge')
    with op.batch_alter_table('medication_statement', schema=None) as batch_op:
        batch_op.drop_index('ix_medstatement_dossier_kind')
        batch_op.drop_index('ix_medstatement_dossier_effective')

    op.drop_table('medication_statement')
    with op.batch_alter_table('dossier_document', schema=None) as batch_op:
        batch_op.drop_index('ix_document_dossier_created')
        batch_op.drop_index('ix_document_dossier_conf')

    op.drop_table('dossier_document')
    with op.batch_alter_table('consent_rule', schema=None) as batch_op:
        batch_op.drop_index('ix_consent_rule_consent')

    op.drop_table('consent_rule')
    with op.batch_alter_table('auth_session', schema=None) as batch_op:
        batch_op.drop_index('ix_session_expires')
        batch_op.drop_index('ix_session_account_state')

    op.drop_table('auth_session')
    with op.batch_alter_table('access_grant', schema=None) as batch_op:
        batch_op.drop_index('ix_grant_grantee_status')
        batch_op.drop_index('ix_grant_dossier_status')

    op.drop_table('access_grant')
    with op.batch_alter_table('professional_credential', schema=None) as batch_op:
        batch_op.drop_index('ix_credential_register')
        batch_op.drop_index('ix_credential_person')

    op.drop_table('professional_credential')
    with op.batch_alter_table('person_role', schema=None) as batch_op:
        batch_op.drop_index('ix_person_role_lookup')

    op.drop_table('person_role')
    with op.batch_alter_table('ledger_anchor_chain', schema=None) as batch_op:
        batch_op.drop_index('ix_anchor_chain_chain')

    op.drop_table('ledger_anchor_chain')
    with op.batch_alter_table('identity_account', schema=None) as batch_op:
        batch_op.drop_index('ix_account_email_index')

    op.drop_table('identity_account')
    op.drop_table('dossier')
    op.drop_table('consent')
    op.drop_table('schema_metadata')
    with op.batch_alter_table('record_revision', schema=None) as batch_op:
        batch_op.drop_index('ix_revision_entity')
        batch_op.drop_index('ix_revision_changed_at')
        batch_op.drop_index('ix_revision_audit_seq')

    op.drop_table('record_revision')
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.drop_index('ix_person_status')
        batch_op.drop_index('ix_person_lookup_index')

    op.drop_table('person')
    op.drop_table('organization')
    with op.batch_alter_table('oidc_flow', schema=None) as batch_op:
        batch_op.drop_index('ix_oidc_flow_expires')

    op.drop_table('oidc_flow')
    with op.batch_alter_table('medicinal_product', schema=None) as batch_op:
        batch_op.drop_index('ix_medicinal_product_name')
        batch_op.drop_index('ix_medicinal_product_authorisation')
        batch_op.drop_index('ix_medicinal_product_atc')

    op.drop_table('medicinal_product')
    with op.batch_alter_table('ledger_anchor', schema=None) as batch_op:
        batch_op.drop_index('ix_ledger_anchor_created')

    op.drop_table('ledger_anchor')
    with op.batch_alter_table('issued_token', schema=None) as batch_op:
        batch_op.drop_index('ix_issued_token_subject')
        batch_op.drop_index('ix_issued_token_expires')

    op.drop_table('issued_token')
    with op.batch_alter_table('audit_event', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_resource')
        batch_op.drop_index('ix_audit_dossier_ts')
        batch_op.drop_index('ix_audit_chain_seq')
        batch_op.drop_index('ix_audit_actor_ts')
        batch_op.drop_index('ix_audit_action_ts')

    op.drop_table('audit_event')
    # ### end Alembic commands ###
